build: Switch from releng/composer-package-php83 to releng/composer-php83
The composer-package-php83 image in CI was discontinued in
I1a675bf156 in favor of composer-php83 and so ships an outdated php-ast
version, because it has been frozen since mid-2025. In particular,
it did not receive the upgrade to phan-ast 1.1.3 from T408653.

This broke Phan at Ie3e710e72d470df468988, because:

> ERROR: Phan 6.x requires php-ast 1.1.3+ because it depends on
> AST version 120. php-ast '1.1.2' is installed.

See also T298008 which updated this in the opposite direction to
a similar issue in 2021. This patch reverts that now to fix the
same issue again in 2026.

Bug: T397429
Bug: T408653
Bug: T298008
Change-Id: I1829e75317b5d0f75a674537e13a6d6d6cda07fe